import type { CardProps } from './types/CardProps'

export const initialCards: Record<string, CardProps> = {
  c1: {
    id: 'c1',
    title: 'Definir escopo e requisitos do projeto',
    description:
      'Reunir todos os requisitos dos stakeholders e definir as fronteiras do projeto com clareza.',
    priority: 'high',
    tags: ['planejamento', 'docs'],
    assignee: 'AM',
    assigneeColor: '#0a84ff',
    dueDate: '2026-04-28',
    columnId: 'backlog',
    createdAt: '2026-04-10',
    attachments: 3,
    comments: 5,
  },
  c2: {
    id: 'c2',
    title: 'Pesquisa de UX com usuários reais',
    description: 'Conduzir entrevistas e testes de usabilidade para validar hipóteses do produto.',
    priority: 'medium',
    tags: ['ux', 'pesquisa'],
    assignee: 'JS',
    assigneeColor: '#bf5af2',
    dueDate: '2026-05-05',
    columnId: 'backlog',
    createdAt: '2026-04-11',
    attachments: 1,
    comments: 2,
  },
  c3: {
    id: 'c3',
    title: 'Configurar pipeline de CI/CD',
    description:
      'Criar pipeline automatizado com testes, lint e deploy para os ambientes de staging e produção.',
    priority: 'low',
    tags: ['devops', 'infraestrutura'],
    assignee: 'RK',
    assigneeColor: '#ff9500',
    columnId: 'backlog',
    createdAt: '2026-04-12',
    attachments: 0,
    comments: 1,
  },
  c4: {
    id: 'c4',
    title: 'Redesign da página de autenticação',
    description:
      'Atualizar fluxos de login, cadastro e recuperação de senha com o novo design system.',
    priority: 'high',
    tags: ['ui', 'auth'],
    assignee: 'LM',
    assigneeColor: '#32d74b',
    dueDate: '2026-05-22',
    columnId: 'todo',
    createdAt: '2026-04-13',
    attachments: 5,
    comments: 8,
  },
  c5: {
    id: 'c5',
    title: 'Implementar dark mode global',
    description: 'Adicionar suporte completo ao dark mode em todos os componentes da aplicação.',
    priority: 'medium',
    tags: ['ui', 'tema'],
    assignee: 'AM',
    assigneeColor: '#0a84ff',
    dueDate: '2026-04-30',
    columnId: 'todo',
    createdAt: '2026-04-14',
    attachments: 0,
    comments: 3,
  },
  c6: {
    id: 'c6',
    title: 'Otimizar queries do banco de dados',
    description:
      'Analisar e otimizar as queries mais lentas identificadas no relatório de performance.',
    priority: 'critical',
    tags: ['backend', 'performance'],
    assignee: 'RK',
    assigneeColor: '#ff9500',
    dueDate: '2026-04-20',
    columnId: 'todo',
    createdAt: '2026-04-14',
    attachments: 2,
    comments: 6,
  },
  c7: {
    id: 'c7',
    title: 'API de notificações em tempo real',
    description:
      'Desenvolver endpoint WebSocket para notificações push com suporte a múltiplos canais.',
    priority: 'high',
    tags: ['backend', 'api'],
    assignee: 'JS',
    assigneeColor: '#bf5af2',
    dueDate: '2026-04-25',
    columnId: 'in-progress',
    createdAt: '2026-04-08',
    attachments: 4,
    comments: 12,
  },
  c8: {
    id: 'c8',
    title: 'Dashboard de analytics',
    description: 'Criar visualizações de dados com gráficos interativos para métricas de negócio.',
    priority: 'medium',
    tags: ['frontend', 'dados'],
    assignee: 'LM',
    assigneeColor: '#32d74b',
    dueDate: '2026-04-26',
    columnId: 'in-progress',
    createdAt: '2026-04-09',
    attachments: 2,
    comments: 7,
  },
  c9: {
    id: 'c9',
    title: 'Migração para TypeScript 5.x',
    description:
      'Atualizar toda a codebase para TypeScript 5.x aproveitando novos recursos da linguagem.',
    priority: 'low',
    tags: ['refactor', 'typescript'],
    assignee: 'AM',
    assigneeColor: '#0a84ff',
    columnId: 'in-progress',
    createdAt: '2026-04-10',
    attachments: 1,
    comments: 4,
  },
  c10: {
    id: 'c10',
    title: 'Testes E2E com Playwright',
    description:
      'Escrever testes end-to-end cobrindo os principais fluxos do usuário na aplicação.',
    priority: 'high',
    tags: ['qa', 'testes'],
    assignee: 'RK',
    assigneeColor: '#ff9500',
    dueDate: '2026-04-21',
    columnId: 'review',
    createdAt: '2026-04-07',
    attachments: 3,
    comments: 9,
  },
  c11: {
    id: 'c11',
    title: 'Documentação da API REST',
    description:
      'Escrever documentação completa com exemplos de uso para todos os endpoints públicos.',
    priority: 'medium',
    tags: ['docs', 'api'],
    assignee: 'JS',
    assigneeColor: '#bf5af2',
    dueDate: '2026-04-23',
    columnId: 'review',
    createdAt: '2026-04-08',
    attachments: 6,
    comments: 3,
  },
  c12: {
    id: 'c12',
    title: 'Setup do monorepo com Turborepo',
    description:
      'Configurar monorepo com Turborepo para gerenciar múltiplos packages de forma eficiente.',
    priority: 'high',
    tags: ['devops', 'arquitetura'],
    assignee: 'LM',
    assigneeColor: '#32d74b',
    columnId: 'done',
    createdAt: '2026-04-01',
    attachments: 2,
    comments: 11,
  },
  c13: {
    id: 'c13',
    title: 'Design tokens e sistema de cores',
    description: 'Definir design tokens para cores, tipografia e espaçamentos do design system.',
    priority: 'medium',
    tags: ['design', 'ui'],
    assignee: 'AM',
    assigneeColor: '#0a84ff',
    columnId: 'done',
    createdAt: '2026-04-02',
    attachments: 8,
    comments: 15,
  },
  c14: {
    id: 'c14',
    title: 'Integração com Stripe Payments',
    description:
      'Integrar gateway de pagamento Stripe com suporte a assinaturas e pagamentos únicos.',
    priority: 'critical',
    tags: ['backend', 'pagamentos'],
    assignee: 'RK',
    assigneeColor: '#ff9500',
    columnId: 'done',
    createdAt: '2026-04-03',
    attachments: 4,
    comments: 20,
  },
}
